### ISSUE TITLE
shelf width

### ISSUE THREAD

**Issue by aliceyliang** [the-pudding/romance-covers-new#21]
overlapping books at the end of certain years:

<img width="496" alt="image" src="https://github.com/the-pudding/romance-covers-new/assets/6892866/c96fa6ad-141f-4cee-9983-f2eebfb3ba44">
<img width="353" alt="image" src="https://github.com/the-pudding/romance-covers-new/assets/6892866/9f2754cc-e8dd-4cf5-bf59-d1948284ce38">

**Comment by jadiehm** [comment]
note: related to resize and vh. shelves not reflowing on screen size. reverted to aboslute w/h for now and will investigate further.
