### ISSUE TITLE
reading list buttons not reacting as expected

### ISSUE THREAD

**Issue by aliceyliang** [the-pudding/romance-covers-new#22]
From time to time these weird factors appear:
1. Sometimes the plus icon appears instead of book icon when removing a book (is this intended?)
2. Sometimes there's no icon at all after being clicked once
3. Sometimes the top right button used to open the reading list is not clickable
<img width="292" alt="image" src="https://github.com/the-pudding/romance-covers-new/assets/6892866/573812c3-71c3-45ea-9725-fae6efd2dcbf">

**Comment by jadiehm** [comment]
@aliceyliang this _might_ be fixed in the newest push to main. it _might_ be related to the reading list being behind one click in the outro section. let me know if you still see weird behavior though! i have an idea of where it's coming from.

**Comment by aliceyliang** [comment]
ok great!! I don't have that previous issue in main anymore but i do think there is still something where some books aren't being added to the list - for example here 6 are clicked and 6 are in the top right number, but 5 are on the list. It doesn't seem to be because of the book, because that book can go on the list sometimes. 
<img width="757" alt="image" src="https://github.com/the-pudding/romance-covers-new/assets/6892866/e8fdf676-e3bd-44d1-865e-c72d6e9b6847">
<img width="246" alt="image" src="https://github.com/the-pudding/romance-covers-new/assets/6892866/c64faa6c-8645-4142-b1b5-e15dcf13f0ea">

**Comment by jadiehm** [comment]
note: ids/classes not resetting on click inside of reading list

**Comment by jadiehm** [comment]
i _think_ i fixed this x2. @aliceyliang  do a screen record if you're still seeing the issue.
