### ISSUE TITLE
wall: books resizing, but throttled leaving orphans

### ISSUE THREAD

**Issue by jadiehm** [the-pudding/romance-covers-new#26]

**Comment by aliceyliang** [comment]
Examples
<img width="923" alt="image" src="https://github.com/the-pudding/romance-covers-new/assets/6892866/f1565109-d8e1-4d26-8fa2-ee9eb68247e2">
<img width="244" alt="image" src="https://github.com/the-pudding/romance-covers-new/assets/6892866/1eb1e46d-e356-4caa-aab1-750123b4fd47">
