### ISSUE TITLE
Scroll behavior between illustration and diversity

### ISSUE THREAD

**Issue by aliceyliang** [the-pudding/romance-covers-new#28]
Two minor things here (screen recording on slack!):
1 - I think I'd like the scroll to go all the way through the end of 2023 even though the copy isn't necessarily about it in the copy. This isn't an issue in the other sections since we highlight 2023 more and there are fewer books in the year. Would the best way to do this be to pick an anchor book toward the end? Or something in the code to enforce that so that it's more responsive regardless of screen size?
2 - If you only scroll to the diversity header (before the copy) the table of contents icons at the top don't change back to illustration if you scroll back up. Edge case issue?

**Comment by jadiehm** [comment]
1. Ahhh, I gotcha. I think the best option would be to add in another invisible step that has no corresponding text, but has a trigger for the scroll attached to the first book OR the last book in 2023. I added that to the Goodle doc and will push it up momentarily.
2. I think I got a hack so that this works.

**Comment by jadiehm** [comment]
1. Oooohhh nope, better idea for this one that I can tackle tomorrow. At the last step (which will still be hidden) we should pop up a scrubbed so people can go back through the years by themselves and see all the books + add ones they missed.

**Comment by jadiehm** [comment]
Basic slider implementation in. Need to recalc for right movement.

**Comment by jadiehm** [comment]
Add hints to interact with slider too.

**Comment by aliceyliang** [comment]
Love the slider!!

Just noting that there are a few unshelved books here - not sure if this is because of the slider addition or something else
<img width="543" alt="image" src="https://github.com/the-pudding/romance-covers-new/assets/6892866/3c89b5d1-b5bd-4a7d-84dd-c47ee0702933">
