### ISSUE TITLE
books where the bookshop link doesn't exist

### ISSUE THREAD

**Issue by aliceyliang** [the-pudding/romance-covers-new#50]
for example: https://bookshop.org/book/9780758292964 doesn't go to anything, seems like it's not actually listed on bookshop. should we just link to https://www.worldcat.org/search?q=bn%3A9780758292964 generally instead which has both library and store options? or programmatically click through them all to check somehow?

**Comment by jadiehm** [comment]
@aliceyliang up to you! worldcat is an extra couple of clicks for people, but it is more neutral than sending people to buy from bookshop. i don't think either is the wrong approach.

**Comment by jadiehm** [comment]
Actually, I just did it! Relevant code [here](https://github.com/the-pudding/romance-covers-new/blob/main/tasks/checkURL.js) and [here](https://github.com/the-pudding/romance-covers-new/blob/main/src/components/ReadingList.svelte).
