### ISSUE TITLE
intro: better placement for small bar charts

### ISSUE THREAD

**Issue by jadiehm** [the-pudding/romance-covers-new#7]

**Comment by jadiehm** [comment]
inline interaction with text

**Comment by aliceyliang** [comment]
@jadiehm in the related branch, I changed colors/hover functions to set the mini charts to inactive and set the text to be hoverable. On the hover, the bar chart could change to active status, e.g. the brighter color. But I wasn't sure what the best way to pass that active status was based on the way the chart is set up - would love your advice!

**Comment by jadiehm** [comment]
@aliceyliang Ah yep! Since the color data is being passed in as a property and coding inline, you can't use regular css classes to get at it. One solution would be to use `.style("background-color`, "#ffffff")` instead of using `.classed()`. I opted for another route after adding the corresponding colors to the spans that just targets the container div and sets the opacity there. No messing with colors and it also de-emphasizes the text associated with the other charts.
